"""create ad_metrics table (partitioned on PostgreSQL, regular on SQLite)

Revision ID: 007
Revises: 006
Create Date: 2026-05-09
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"

    if is_postgresql:
        # Partitioned table — pg_partman manages monthly partitions
        op.execute("""
            CREATE TABLE ad_metrics (
                id BIGSERIAL,
                client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
                report_type VARCHAR(50) NOT NULL,
                metric_date DATE NOT NULL,
                grain_type VARCHAR(20) NOT NULL,
                campaign_id BIGINT NOT NULL,
                campaign_name VARCHAR(500),
                campaign_status VARCHAR(50),
                campaign_budget_amount NUMERIC(12,2),
                campaign_budget_type VARCHAR(50),
                campaign_budget_currency VARCHAR(10),
                portfolio_id BIGINT,
                ad_group_id BIGINT,
                ad_group_name VARCHAR(500),
                keyword_id BIGINT,
                keyword VARCHAR(500),
                keyword_text VARCHAR(500),
                keyword_type VARCHAR(50),
                keyword_bid NUMERIC(10,4),
                ad_keyword_status VARCHAR(50),
                match_type VARCHAR(50),
                targeting_id BIGINT,
                targeting_text VARCHAR(500),
                targeting_type VARCHAR(50),
                targeting_expression TEXT,
                search_term VARCHAR(500),
                ad_id BIGINT,
                ad_name VARCHAR(500),
                advertised_asin VARCHAR(20),
                advertised_sku VARCHAR(255),
                promoted_asin VARCHAR(20),
                promoted_sku VARCHAR(255),
                bid_optimization VARCHAR(50),
                impressions INTEGER NOT NULL DEFAULT 0,
                viewable_impressions INTEGER,
                impressions_views INTEGER,
                impressions_frequency_avg NUMERIC(8,4),
                clicks INTEGER NOT NULL DEFAULT 0,
                cost NUMERIC(12,4) NOT NULL DEFAULT 0,
                cost_type VARCHAR(10),
                cost_per_click NUMERIC(10,4),
                click_through_rate NUMERIC(12,6),
                view_click_through_rate NUMERIC(10,4),
                viewability_rate NUMERIC(10,4),
                top_of_search_impression_share NUMERIC(10,4),
                purchase_click_rate_14d NUMERIC(10,4),
                sales_14d NUMERIC(12,2),
                sales_1d NUMERIC(12,2),
                sales_7d NUMERIC(12,2),
                sales_30d NUMERIC(12,2),
                attributed_sales_same_sku_1d NUMERIC(12,2),
                attributed_sales_same_sku_7d NUMERIC(12,2),
                attributed_sales_same_sku_14d NUMERIC(12,2),
                attributed_sales_same_sku_30d NUMERIC(12,2),
                sales_other_sku_7d NUMERIC(12,2),
                sales_other_sku_14d NUMERIC(12,2),
                sales NUMERIC(12,2),
                sales_clicks NUMERIC(12,2),
                sales_promoted NUMERIC(12,2),
                sales_promoted_clicks NUMERIC(12,2),
                purchases_14d INTEGER,
                purchases_1d INTEGER,
                purchases_7d INTEGER,
                purchases_30d INTEGER,
                purchases_same_sku_1d INTEGER,
                purchases_same_sku_7d INTEGER,
                purchases_same_sku_14d INTEGER,
                purchases_same_sku_30d INTEGER,
                purchases INTEGER,
                purchases_clicks INTEGER,
                purchases_promoted INTEGER,
                units_sold_clicks_14d INTEGER,
                units_sold_clicks_1d INTEGER,
                units_sold_clicks_7d INTEGER,
                units_sold_clicks_30d INTEGER,
                units_sold_same_sku_1d INTEGER,
                units_sold_same_sku_7d INTEGER,
                units_sold_same_sku_14d INTEGER,
                units_sold_same_sku_30d INTEGER,
                units_sold_other_sku_7d INTEGER,
                units_sold_other_sku_14d INTEGER,
                units_sold INTEGER,
                units_sold_clicks INTEGER,
                acos_clicks_7d NUMERIC(10,4),
                acos_clicks_14d NUMERIC(10,4),
                roas_clicks_7d NUMERIC(10,4),
                roas_clicks_14d NUMERIC(10,4),
                detail_page_views INTEGER,
                detail_page_views_clicks INTEGER,
                add_to_cart INTEGER,
                add_to_cart_clicks INTEGER,
                add_to_cart_views INTEGER,
                add_to_cart_rate NUMERIC(10,4),
                ecp_add_to_cart NUMERIC(10,4),
                add_to_list INTEGER,
                add_to_list_from_clicks INTEGER,
                add_to_list_from_views INTEGER,
                new_to_brand_sales NUMERIC(12,2),
                new_to_brand_sales_clicks NUMERIC(12,2),
                new_to_brand_sales_pct NUMERIC(10,4),
                new_to_brand_purchases INTEGER,
                new_to_brand_purchases_clicks INTEGER,
                new_to_brand_purchases_rate NUMERIC(10,4),
                new_to_brand_purchases_pct NUMERIC(10,4),
                new_to_brand_units_sold INTEGER,
                new_to_brand_units_sold_clicks INTEGER,
                new_to_brand_units_sold_pct NUMERIC(10,4),
                new_to_brand_dpv INTEGER,
                new_to_brand_dpv_clicks INTEGER,
                new_to_brand_dpv_views INTEGER,
                new_to_brand_dpv_rate NUMERIC(10,4),
                new_to_brand_ecp_dpv NUMERIC(10,4),
                video_5s_views INTEGER,
                video_5s_view_rate NUMERIC(10,4),
                video_complete_views INTEGER,
                video_first_quartile_views INTEGER,
                video_midpoint_views INTEGER,
                video_third_quartile_views INTEGER,
                video_unmutes INTEGER,
                branded_searches INTEGER,
                branded_searches_clicks INTEGER,
                branded_searches_views INTEGER,
                branded_search_rate NUMERIC(10,4),
                ecp_brand_search NUMERIC(10,4),
                cumulative_reach INTEGER,
                lead_form_opens INTEGER,
                leads INTEGER,
                link_outs INTEGER,
                landing_page_url TEXT,
                kindle_pages_read_14d INTEGER,
                kindle_pages_royalties_14d NUMERIC(12,4),
                qualified_borrows INTEGER,
                qualified_borrows_clicks INTEGER,
                qualified_borrows_views INTEGER,
                royalty_qualified_borrows INTEGER,
                royalty_qualified_borrows_clicks INTEGER,
                royalty_qualified_borrows_views INTEGER,
                retailer VARCHAR(50),
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, metric_date)
            ) PARTITION BY RANGE (metric_date);
        """)
        # Default partition catches all data until month-specific ones are added
        op.execute("""
            CREATE TABLE ad_metrics_default PARTITION OF ad_metrics DEFAULT;
        """)
    else:
        # SQLite — regular table, no partitioning
        op.create_table(
            "ad_metrics",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("client_id", sa.Integer, sa.ForeignKey("clients.id", ondelete="CASCADE"), nullable=False),
            sa.Column("report_type", sa.String(50), nullable=False),
            sa.Column("metric_date", sa.Date, nullable=False),
            sa.Column("grain_type", sa.String(20), nullable=False),
            sa.Column("campaign_id", sa.BigInteger, nullable=False),
            sa.Column("campaign_name", sa.String(500), nullable=True),
            sa.Column("campaign_status", sa.String(50), nullable=True),
            sa.Column("campaign_budget_amount", sa.Numeric(12, 2), nullable=True),
            sa.Column("campaign_budget_type", sa.String(50), nullable=True),
            sa.Column("campaign_budget_currency", sa.String(10), nullable=True),
            sa.Column("portfolio_id", sa.BigInteger, nullable=True),
            sa.Column("ad_group_id", sa.BigInteger, nullable=True),
            sa.Column("ad_group_name", sa.String(500), nullable=True),
            sa.Column("keyword_id", sa.BigInteger, nullable=True),
            sa.Column("keyword", sa.String(500), nullable=True),
            sa.Column("keyword_text", sa.String(500), nullable=True),
            sa.Column("keyword_type", sa.String(50), nullable=True),
            sa.Column("keyword_bid", sa.Numeric(10, 4), nullable=True),
            sa.Column("ad_keyword_status", sa.String(50), nullable=True),
            sa.Column("match_type", sa.String(50), nullable=True),
            sa.Column("targeting_id", sa.BigInteger, nullable=True),
            sa.Column("targeting_text", sa.String(500), nullable=True),
            sa.Column("targeting_type", sa.String(50), nullable=True),
            sa.Column("targeting_expression", sa.Text, nullable=True),
            sa.Column("search_term", sa.String(500), nullable=True),
            sa.Column("ad_id", sa.BigInteger, nullable=True),
            sa.Column("ad_name", sa.String(500), nullable=True),
            sa.Column("advertised_asin", sa.String(20), nullable=True),
            sa.Column("advertised_sku", sa.String(255), nullable=True),
            sa.Column("promoted_asin", sa.String(20), nullable=True),
            sa.Column("promoted_sku", sa.String(255), nullable=True),
            sa.Column("bid_optimization", sa.String(50), nullable=True),
            sa.Column("impressions", sa.Integer, nullable=False, server_default="0"),
            sa.Column("viewable_impressions", sa.Integer, nullable=True),
            sa.Column("impressions_views", sa.Integer, nullable=True),
            sa.Column("impressions_frequency_avg", sa.Numeric(8, 4), nullable=True),
            sa.Column("clicks", sa.Integer, nullable=False, server_default="0"),
            sa.Column("cost", sa.Numeric(12, 4), nullable=False, server_default="0"),
            sa.Column("cost_type", sa.String(10), nullable=True),
            sa.Column("cost_per_click", sa.Numeric(10, 4), nullable=True),
            sa.Column("click_through_rate", sa.Numeric(12, 6), nullable=True),
            sa.Column("view_click_through_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("viewability_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("top_of_search_impression_share", sa.Numeric(10, 4), nullable=True),
            sa.Column("purchase_click_rate_14d", sa.Numeric(10, 4), nullable=True),
            sa.Column("sales_14d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_1d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_7d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_30d", sa.Numeric(12, 2), nullable=True),
            sa.Column("attributed_sales_same_sku_1d", sa.Numeric(12, 2), nullable=True),
            sa.Column("attributed_sales_same_sku_7d", sa.Numeric(12, 2), nullable=True),
            sa.Column("attributed_sales_same_sku_14d", sa.Numeric(12, 2), nullable=True),
            sa.Column("attributed_sales_same_sku_30d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_other_sku_7d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_other_sku_14d", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_clicks", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_promoted", sa.Numeric(12, 2), nullable=True),
            sa.Column("sales_promoted_clicks", sa.Numeric(12, 2), nullable=True),
            sa.Column("purchases_14d", sa.Integer, nullable=True),
            sa.Column("purchases_1d", sa.Integer, nullable=True),
            sa.Column("purchases_7d", sa.Integer, nullable=True),
            sa.Column("purchases_30d", sa.Integer, nullable=True),
            sa.Column("purchases_same_sku_1d", sa.Integer, nullable=True),
            sa.Column("purchases_same_sku_7d", sa.Integer, nullable=True),
            sa.Column("purchases_same_sku_14d", sa.Integer, nullable=True),
            sa.Column("purchases_same_sku_30d", sa.Integer, nullable=True),
            sa.Column("purchases", sa.Integer, nullable=True),
            sa.Column("purchases_clicks", sa.Integer, nullable=True),
            sa.Column("purchases_promoted", sa.Integer, nullable=True),
            sa.Column("units_sold_clicks_14d", sa.Integer, nullable=True),
            sa.Column("units_sold_clicks_1d", sa.Integer, nullable=True),
            sa.Column("units_sold_clicks_7d", sa.Integer, nullable=True),
            sa.Column("units_sold_clicks_30d", sa.Integer, nullable=True),
            sa.Column("units_sold_same_sku_1d", sa.Integer, nullable=True),
            sa.Column("units_sold_same_sku_7d", sa.Integer, nullable=True),
            sa.Column("units_sold_same_sku_14d", sa.Integer, nullable=True),
            sa.Column("units_sold_same_sku_30d", sa.Integer, nullable=True),
            sa.Column("units_sold_other_sku_7d", sa.Integer, nullable=True),
            sa.Column("units_sold_other_sku_14d", sa.Integer, nullable=True),
            sa.Column("units_sold", sa.Integer, nullable=True),
            sa.Column("units_sold_clicks", sa.Integer, nullable=True),
            sa.Column("acos_clicks_7d", sa.Numeric(10, 4), nullable=True),
            sa.Column("acos_clicks_14d", sa.Numeric(10, 4), nullable=True),
            sa.Column("roas_clicks_7d", sa.Numeric(10, 4), nullable=True),
            sa.Column("roas_clicks_14d", sa.Numeric(10, 4), nullable=True),
            sa.Column("detail_page_views", sa.Integer, nullable=True),
            sa.Column("detail_page_views_clicks", sa.Integer, nullable=True),
            sa.Column("add_to_cart", sa.Integer, nullable=True),
            sa.Column("add_to_cart_clicks", sa.Integer, nullable=True),
            sa.Column("add_to_cart_views", sa.Integer, nullable=True),
            sa.Column("add_to_cart_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("ecp_add_to_cart", sa.Numeric(10, 4), nullable=True),
            sa.Column("add_to_list", sa.Integer, nullable=True),
            sa.Column("add_to_list_from_clicks", sa.Integer, nullable=True),
            sa.Column("add_to_list_from_views", sa.Integer, nullable=True),
            sa.Column("new_to_brand_sales", sa.Numeric(12, 2), nullable=True),
            sa.Column("new_to_brand_sales_clicks", sa.Numeric(12, 2), nullable=True),
            sa.Column("new_to_brand_sales_pct", sa.Numeric(10, 4), nullable=True),
            sa.Column("new_to_brand_purchases", sa.Integer, nullable=True),
            sa.Column("new_to_brand_purchases_clicks", sa.Integer, nullable=True),
            sa.Column("new_to_brand_purchases_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("new_to_brand_purchases_pct", sa.Numeric(10, 4), nullable=True),
            sa.Column("new_to_brand_units_sold", sa.Integer, nullable=True),
            sa.Column("new_to_brand_units_sold_clicks", sa.Integer, nullable=True),
            sa.Column("new_to_brand_units_sold_pct", sa.Numeric(10, 4), nullable=True),
            sa.Column("new_to_brand_dpv", sa.Integer, nullable=True),
            sa.Column("new_to_brand_dpv_clicks", sa.Integer, nullable=True),
            sa.Column("new_to_brand_dpv_views", sa.Integer, nullable=True),
            sa.Column("new_to_brand_dpv_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("new_to_brand_ecp_dpv", sa.Numeric(10, 4), nullable=True),
            sa.Column("video_5s_views", sa.Integer, nullable=True),
            sa.Column("video_5s_view_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("video_complete_views", sa.Integer, nullable=True),
            sa.Column("video_first_quartile_views", sa.Integer, nullable=True),
            sa.Column("video_midpoint_views", sa.Integer, nullable=True),
            sa.Column("video_third_quartile_views", sa.Integer, nullable=True),
            sa.Column("video_unmutes", sa.Integer, nullable=True),
            sa.Column("branded_searches", sa.Integer, nullable=True),
            sa.Column("branded_searches_clicks", sa.Integer, nullable=True),
            sa.Column("branded_searches_views", sa.Integer, nullable=True),
            sa.Column("branded_search_rate", sa.Numeric(10, 4), nullable=True),
            sa.Column("ecp_brand_search", sa.Numeric(10, 4), nullable=True),
            sa.Column("cumulative_reach", sa.Integer, nullable=True),
            sa.Column("lead_form_opens", sa.Integer, nullable=True),
            sa.Column("leads", sa.Integer, nullable=True),
            sa.Column("link_outs", sa.Integer, nullable=True),
            sa.Column("landing_page_url", sa.Text, nullable=True),
            sa.Column("kindle_pages_read_14d", sa.Integer, nullable=True),
            sa.Column("kindle_pages_royalties_14d", sa.Numeric(12, 4), nullable=True),
            sa.Column("qualified_borrows", sa.Integer, nullable=True),
            sa.Column("qualified_borrows_clicks", sa.Integer, nullable=True),
            sa.Column("qualified_borrows_views", sa.Integer, nullable=True),
            sa.Column("royalty_qualified_borrows", sa.Integer, nullable=True),
            sa.Column("royalty_qualified_borrows_clicks", sa.Integer, nullable=True),
            sa.Column("royalty_qualified_borrows_views", sa.Integer, nullable=True),
            sa.Column("retailer", sa.String(50), nullable=True),
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        )

    op.create_index("ix_ad_metrics_client_date", "ad_metrics", ["client_id", "metric_date"])
    op.create_index("ix_ad_metrics_client_campaign_date", "ad_metrics", ["client_id", "campaign_id", "metric_date"])
    op.create_index("ix_ad_metrics_search_term", "ad_metrics", ["client_id", "search_term"])
    op.create_index("ix_ad_metrics_asin_date", "ad_metrics", ["advertised_asin", "metric_date"])
    op.create_index("ix_ad_metrics_grain", "ad_metrics", ["grain_type"])


def downgrade() -> None:
    op.drop_table("ad_metrics")
